export const Package = {
  BOTELLA: 'Botella',
  LATA: 'Lata',
  BARRIL: 'Barril',
  TETRAPACK: 'Tetrapack'
}

export const Category = {
  CERVEZAS: 'Cervezas',
  VINOS: 'Vinos',
  DESTILADOS: 'Destilados'
}

export const SubCategory = {
  CERVEZAS_ARTESANALES: 'Cervezas Artesanales',
  CERVEZAS_TRADICIONALES: 'Cervezas Tradicionales',
  CERVEZAS_IMPORTADAS: 'Cervezas Importadas',
  CERVEZAS_SIN_ALCOHOL: 'Cervezas Sin Alcohol',
  VINOS_TINTOS: 'Vinos Tintos',
  VINOS_BLANCOS: 'Vinos Blancos',
  VINOS_ROSE: 'Vinos Rosé',
  VINOS_CERO: 'Vinos Cero',
  PISCO: 'Pisco',
  RON: 'Ron',
  TEQUILA: 'Tequila',
  VODKA: 'Vodka',
  WHISKEY: 'Whisky',
  GIN: 'Gin'
}

export const Variety = {
  // antes
  ALE: 'Ale',
  NEGRA: 'Negra',
  IPA: 'IPA',
  TRIGO: 'Trigo',
  FRUIT: 'Fruit',
  // Escuela Alemana
  LAGER: 'Lager',
  PALE_LAGER: 'Pale Lager',
  GERMAN_PILS: 'German Pils',
  MUNICH: 'Munich',
  DUNKEL: 'Dunkel',
  OKTOBERFEST: 'Oktoberfest',
  BOCK: 'Bock',
  HELLER_BOCK: 'Heller Bock',
  DUNKLER_BOCK: 'Dunkler Bock',
  DOPPELBOCK: 'Doppelbock',
  EISBOCK: 'Eisbock',
  SCHWARZBIER: 'Schwarzbier',
  KELLERBIER: 'Kellerbier',
  RAUCHBIER: 'Rauchbier',
  WEIZEN: 'Weizen',
  HEFEWEIZEN: 'Hefeweizen',
  KRISTALLWEIZEN: 'Kristallweizen',
  DUNKELWEIZEN: 'Dunkelweizen',
  WEIZENBOCK: 'Weizenbock',
  KOLSCH: 'Kölsch',
  ALTBIER: 'Altbier',
  BERLINER_WEISSE: 'Berliner Weisse',
  GOSE: 'Gose',
  // Escuela Britanica
  CASK_ALE: 'Cask Ale',
  ORDINARY_BITTER: 'Ordinary Bitter',
  BEST_BITTER: 'Best Bitter',
  STRONG_BITTER: 'Strong Bitter',
  BRITISH_PALE_ALE: 'British Pale Ale',
  PORTER: 'Porter',
  STOUT: 'Stout',
  IMPERIAL_STOUT: 'Imperial Stout',
  BROWN_ALE: 'Brown Ale',
  SCOTCH_ALE: 'Scotch Ale',
  IRISH_RED_ALE: 'Irish Red Ale',
  // Escuela Belga
  ABBEY_ALES: 'Abbey Ales',
  SINGLE: 'Single',
  DUBBEL: 'Dubbel',
  TRIPEL: 'Triple',
  QUADRUPEL: 'Quadrupel',
  BELGIAN_GOLDEN_STRONG_ALE: 'Belgian Golden Strong Ale',
  BELGIAN_STRONG_DARK_ALE: 'Belgian Strong Dark Ale',
  BELGIAN_STRONG_PALE_ALE: 'Belgian Strong Pale Ale',
  FARMHOUSE_ALE: 'Farmhouse Ale',
  SAISON: 'Saison',
  BIERE_DE_GARDE: 'Bière de Garde',
  BELGIAN_BLONDE_ALE: 'Belgian Blonde Ale',
  WITBIER: 'Witbier',
  WHEAT_ALE: 'Wheat Ale',
  DARK_ALE: 'Dark Ale',
  PALE_ALE: 'Pale Ale',
  GOLDEN_ALE: 'Golden Ale',
  LAMBIC: 'Lambic',
  FLANDERS_RED_ALE: 'Flanders Red Ale',
  FLANDERS_BROWN_ALE: 'Flanders Brown Ale',
  // Escuela EEUU
  AMERICAN_PALE_ALE: 'American Pale Ale',
  INDIAN_PALE_ALE: 'Indian Pale Ale',
  HAZY_IPA: 'Hazy IPA',
  DOUBLE_HAZY_IPA: 'Double Hazy IPA',
  AMERICAN_PORTER: 'American Porter',
  AMERICAN_IMPERIAL_STOUT: 'American Imperial Stout',
  AMERICAN_SCOTCH_ALE: 'American Scotch Ale'
}

export const Strain = {
  CABERNET_SAUVIGNON: 'Cabernet Sauvignon',
  PINOT_NOIR: 'Pinot Noir',
  MERLOT: 'Merlot',
  SYRAH: 'Syrah',
  CARMENERE: 'Carmenere',
  MALBEC: 'Malbec',
  SAUVIGNON_BLANC: 'Sauvignon Blanc',
  CHARDONNAY: 'Chardonnay',
  PINOT_GRIGIO: 'Pinot Grigio',
  PINOT_GRIS: 'Pinot Gris',
  ALBARINO: 'Albariño',
  MOSCATO: 'Moscato',
  MOSCATEL: 'Moscatel',
  VERDEJO: 'Verdejo',
  RIESLING: 'Riesling',
  SEMILLON: 'Semillón',
  GEWURZTRAMINER: 'Gewürztraminer',
  GARNACHA: 'Garnacha',
  TEMPERANILLO: 'Temperanillo',
  SANGIOVESE: 'Sangiovese',
  ZINFANDEL: 'Zinfandel'
}
